config/routes.rb
Varietal::Application.routes.draw do
  
  devise_for :users
  resources :claim_places do
    resources :products
  end

  resources :coffeeintro

  root :to => 'claim_places#index'
  

end

app/models/claim_place.rb
class ClaimPlace < ActiveRecord::Base
  validates :storeName, :presence => true
  validates :address, :presence => true
  # validates_presence_of :latitude
  # validates_presence_of :longitude

  belongs_to :claimer, :class_name => "User", :foreign_key => :userid
  belongs_to :owner, :class_name => "User", :foreign_key => :owner_user_id

  has_many :products

  def editable_by?(user)
     user && user == claimer
  end


end

app/controllers/claim_places_controller.rb
class ClaimPlacesController < ApplicationController
  include ActiveModel::ForbiddenAttributesProtection

  before_filter :login_required, :only => [:new, :create, :edit, :update, :destroy]

  respond_to :json, :html, :xml

  def index
    @claimPlace = ClaimPlace.all.reverse
    
    respond_to do |format|
     format.html #index.html.erb.erb
     format.xml {render :xml => @claimPlace}
     format.json { render :json => @claimPlace.to_json }
    end
  end

  def show
    @claimPlace = ClaimPlace.find(params[:id])
    
    respond_with(@products = @claimPlace.products.reverse)
  end

  def new
    @claimPlace = ClaimPlace.new
  end

  def create
    #@claimPlace = ClaimPlace.new(claim_place_params)
    @claimPlace = current_user.claim_places.build(claim_place_params)

    # Rails.logger.debug("ClaimPlace!: #{@claimPlace.inspect}")
    #Rails.logger.debug("current_user: #{@claimPlace.inspect}")
    Rails.logger.debug("longitude!: #{@claimPlace.longitude}")

    if @claimPlace.save
      Rails.logger.debug("ClaimPlace was saved !!!")
      redirect_to claim_places_path
    else
      Rails.logger.debug("ClaimPlace wasn't saved !!!")

      render :new
    end
  end

  def edit
    #@claimPlace = ClaimPlace.find(params[:id])
    @claimPlace = current_user.claim_places.find(params[:id])
  end

  # form被包成一個hash，如果能夠接參數進行更新及儲存
  # 就會重導到 SHOW ACTION 失敗則退回到 EDIT ACTION
  def update
    #@claimPlace = ClaimPlace.find(params[:id])

    @claimPlace = current_user.claim_places.find(params[:id])

    if @claimPlace.update_attributes(claim_place_params)
      redirect_to claim_place_path(@claimPlace)
    else
      render :edit
    end
  end

  def destroy
    #@claimPlace = ClaimPlace.find(params[:id])
    @claimPlace = current_user.claim_places.find(params[:id])
    @claimPlace.destroy

    redirect_to claim_place_path
  end


  private
    def claim_place_params
      params.require(:claim_place).permit(:storeName, :address, :ownerPhone, :ownerEmail, :ownerWebsite, :owner, :description, :latitude, :longitude)
      # params[:claim_place].slice(:storeName, :address, :ownerEmail, :ownerPhone, :description, :owner, :ownerWebsite)
    end



end

app/helpers/claim_places_helper.rb
module ClaimPlacesHelper
end

app/views/claim_places/edit.html.erb
<div class="container" style="margin-top: 200px;">

  <%= simple_form_for @claimPlace do |f| %>
    <%= f.input :storeName,
                label:'Store Name',
                :input_html => { :class => "input-medium" } %>

    <%= f.input :address,
                label: 'Store Address',
                :input_html => { :class => "input-xxlarge"} %>

    <%= f.input :ownerPhone,
                label:'Store Phone',
                :input_html => { :class => "input-medium" } %>

    <%= f.input :ownerEmail,
                label:'Store Email',
                :input_html => { :class => "input-xlarge" } %>

    <%= f.input :ownerWebsite,
                label:'Store Website',
                :input_html => { :class => "input-xlarge" } %>


    <%= f.cktext_area :description, 
                :input_html => { :class => "ckeditor input-xxlarge" } %>

    <div class="form-actions">

      <%= f.submit "Submit", :disable_with => 'Submiting...',
                   :class => "btn btn-primary"%>
    </div>
  <% end %>

</div>

app/views/claim_places/index.html.erb
<div class="carousel">
  <div class="carousel-inner">
    <div class="active item five"></div>
  </div>
</div>

<div class="claimPlacesContainer container">

  <div class="row-fluid">
    <div class="btn-group">
      <button id="claimPlace" class="btn btn-info btn-large claimNewPlaceButton" role="button"
              onclick="document.location.href='<%= new_claim_place_path %>';return false;"
              >
        Create Store
      </button>
    </div>
  </div>
  
<!--   <section id="options" class="clearfix">
    <h3>Sort</h3>
    <ul id="sort-by" class="option-set clearfix" data-option-key="sortBy">
      <li>
        <a href="#sortBy=name" data-option-value="name">name</a>
      </li>
    </ul>
  </section> -->

	<div id="placeListContainer">
		<% @claimPlace.each_with_index do |place,index| %>
			<div class="isotopeStore">
				<a class="placesName" href="<%= claim_place_path(place.id) %>">
					<%= place.storeName %>
				</a>	
        
        <div class="placesAddress">
          <%= place.address %>
        </div>
					
        <a class="placesWebsite" href="http://<%= place.ownerWebsite %>">
          <%= place.ownerWebsite %> 
        </a>

        <div class="placesEmail">
					<%= place.ownerEmail %>
				</div>
			</div>
		<% end %>
	</div>
</div>







<script type="text/javascript">
  var $optionSets = $('#options .option-set'),
      $optionsLinks = $optionSets.find('a');

  $optionsLinks.click(function(){
    var $this = $(this);
    // don't proceed if already selected
    if ( $this.hasClass('selected') ) {
      return false;
    }
    var $optionSet = $this.parents('.option-set');
    $optionSet.find('.selected').removeClass('selected');
    $this.addClass('selected');

    // make option object dynamically, i.e. { filter: '.my-filter-class' }
    var options = {},
        key = $optionSet.attr('data-option-key'),
        value = $this.attr('data-option-value');
    // parse 'false' as false boolean
    value = value === 'false' ? false : value;
    options[ key ] = value;
    if ( key === 'layoutMode' && typeof changeLayoutMode === 'function' ) {
      // changes in layout modes need extra logic
      changeLayoutMode( $this, options )
    } else {
      // otherwise, apply new options
      $container.isotope( options );
    }
    
    return false;    
  });


</script>

<script type="text/css">
#options ul {
  margin: 0;
  list-style: none;
}

#options li a.select{
  backbround-color: #13F;
  text-shadow: none;
  color: white;
}

#options li {
  float: left;
  margin-bottom: 0.2em;
}

#options li a {
  border-left: 1px solid hsla(0, 0%, 100%, 0.3);
  border-right: 1px solid hsla(0, 0%, 0%, 0.2);
}

#options li a {
  display: block;
  padding: 0.4em 0.5em;
  background-color: #DDD;
  color: #222;
  font-weight: bold;
  text-shadow: 0 1px hsla( 0, 0%, 100%, 0.5 );
  background-image: -webkit-linear-gradient( top, hsla( 0, 0%, 100%, 0.5 ), hsla( 0, 0%, 100%, 0.0 ) );
  background-image: -moz-linear-gradient( top, hsla( 0, 0%, 100%, 0.5 ), hsla( 0, 0%, 100%, 0.0 ) );
  background-image: -ms-linear-gradient( top, hsla( 0, 0%, 100%, 0.5 ), hsla( 0, 0%, 100%, 0.0 ) );
  background-image: -o-linear-gradient( top, hsla( 0, 0%, 100%, 0.5 ), hsla( 0, 0%, 100%, 0.0 ) );
  background-image: linear-gradient( top, hsla( 0, 0%, 100%, 0.5 ), hsla( 0, 0%, 100%, 0.0 ) );
}

/**** Isotope Filtering ****/

.isotope-item {
  z-index: 2;
}

.isotope-hidden.isotope-item {
  pointer-events: none;
  z-index: 1;
}

/**** Isotope CSS3 transitions ****/

.isotope,
.isotope .isotope-item {
  -webkit-transition-duration: 0.8s;
     -moz-transition-duration: 0.8s;
      -ms-transition-duration: 0.8s;
       -o-transition-duration: 0.8s;
          transition-duration: 0.8s;
}

.isotope {
  -webkit-transition-property: height, width;
     -moz-transition-property: height, width;
      -ms-transition-property: height, width;
       -o-transition-property: height, width;
          transition-property: height, width;
}

.isotope .isotope-item {
  -webkit-transition-property: -webkit-transform, opacity;
     -moz-transition-property:    -moz-transform, opacity;
      -ms-transition-property:     -ms-transform, opacity;
       -o-transition-property:      -o-transform, opacity;
          transition-property:         transform, opacity;
}

/**** disabling Isotope CSS3 transitions ****/

.isotope.no-transition,
.isotope.no-transition .isotope-item,
.isotope .isotope-item.no-transition {
  -webkit-transition-duration: 0s;
     -moz-transition-duration: 0s;
      -ms-transition-duration: 0s;
       -o-transition-duration: 0s;
          transition-duration: 0s;
}

</script>

app/views/claim_places/new.html.erb
<script type="text/javascript"
        src="https://maps.googleapis.com/maps/api/js?libraries=places&key=AIzaSyAqPJM7UHDfLFx5a8v192BuKLi7BAN69_s">
</script>
<script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
<link href="//ajax.googleapis.com/ajax/libs/jqueryui/1.8.9/themes/base/jquery-ui.css" rel="stylesheet" type="text/css"/>

<div id="map-canvas"></div>

<div class="searchbar">
  <div class=" searchWraper">
      <input type="text" value="" id="searchbox" class="controls" placeholder='Search Address'>

      <button id="search" class="newPlacesBtn" role="button"
              onclick="searchPlace();">
        Search
      </button>

      <button id="create" class="newPlacesBtn" role="button"
              onclick="createPlace();">
        Create
      </button>
  </div>
  <!-- <div class=" searchWraper col-lg-3 col-lg-offset-7">
      <input type="text" value="" id="searchbox" class="col-lg-12" placeholder='Search Address'>

      <button id="search" class="btn btn-info col-xs-2 col-sm-2 col-md-2 col-lg-2" role="button"
              onclick="searchPlace();">
        Search
      </button>

      <button id="create" class="btn btn-info col-xs-2 col-sm-2 col-md-2 col-lg-2" role="button"
              onclick="createPlace();">
        Create
      </button>
  </div> -->
  <!-- <div class="navbar offset2 suspensionForm"> -->
</div>

<div class="navWraper suspensionWraper createPlaceWraper" style="display:none">    
  <%= simple_form_for @claimPlace,:html => {:class => "suspensionForm col-lg-5 col-lg-offset-7"}  do |f| %>
    <%= f.input :storeName,
                label:'Store Name',
                :input_html => { :class => "suspensionIputMideum" } %>

    <!-- <div class="control-group string required claim_place_address">
      <label class="string required control-label" for="createPlaceAddress">
        <abbr title="required">*</abbr> Address
      </label>

      <div class="controls">
        <div id="createPlaceAddress" class="string required suspensionInputLarge"></div>

      </div>
    </div> -->

    <%= f.input :address,
                label:'Address',
                :input_html => { :class => "suspensionInputLarge" } %>

    <%= f.input :ownerPhone,
                label:'Phone',
                :input_html => { :class => "suspensionInputMideum" } %>

    <%= f.input :ownerEmail,
                label:'Email',
                :input_html => { :class => "suspensionInputMideum" } %>

    <%= f.input :ownerWebsite,
                label:'Website',
                :input_html => { :class => "suspensionInputMideum" } %>

    <%= f.input :latitude,
                :as => :hidden,
                :input_html => { :id => "createPlaceLat", :value => 0.0 } %>
    <%= f.input :longitude,
                :as => :hidden,
                :input_html => { :id => "createPlaceLng", :value => 0.0 } %>

    <!-- %= f.input :owner,
                label:'Are you Store Owner ?',
                as: :radio_buttons
    %>
    %= f.input :description, as: :text, :input_html => { :class => "input-xxlarge"} %> -->

    <div class="form-actions">
      <%= f.submit "Claim Store !", :disable_with => 'Submiting...',
                   :class => "btn btn-primary suspensionButton"%>
    </div>
  <% end %>
</div>

<!-- <div class="span4 offset12">
  <img src="/assets/powered-by-google-on-white.png"/>
</div> -->  

<script type="text/javascript">
  var geocoder = new google.maps.Geocoder();
  // Taipei 101
  var loclat = 25.033493
  var loclng = 121.564101

  var mapOptions = {
    zoom: 18,
    center: new google.maps.LatLng(loclat,loclng),
    mapTypeId: google.maps.MapTypeId.ROADMAP,
    mapTypeControl: true,
    mapTypeControlOptions: {
      style: google.maps.MapTypeControlStyle.DROPDOWN_MENU
    },
    zoomControl: true,
    zoomControlOptions: {
      style: google.maps.ZoomControlStyle.SMALL,
      position: google.maps.ControlPosition.RIGHT_CENTER
    },
    // disableDefaultUI: false,
    panControl: true,
    panControlOptions:{
      position: google.maps.ControlPosition.RIGHT_CENTER
    },
    scaleControl: true,
    streetViewControl: true
  }

  $(document).ready(function(){

    var map = new google.maps.Map(document.getElementById("map-canvas"),mapOptions);

    new google.maps.Marker({
      position: new google.maps.LatLng(loclat,loclng),
      map: map,
      title: "Taiwan Taipei 101"
    });

    $(function() {
      //Google Map 自動完成提示
      $("#searchbox").autocomplete({
        source: function(request, response) {

          if (geocoder == null){
            geocoder = new google.maps.Geocoder();
          }
          geocoder.geocode( {'address': request.term }, function(results, status) {
            if (status == google.maps.GeocoderStatus.OK) {

              var searchLoc = results[0].geometry.location;
              var lat = results[0].geometry.location.lat();
              var lng = results[0].geometry.location.lng();
              var latlng = new google.maps.LatLng(lat, lng);
              var bounds = results[0].geometry.bounds;

              geocoder.geocode({'latLng': latlng}, function(results1, status1) {
                if (status1 == google.maps.GeocoderStatus.OK) {
                  if (results1[1]) {
                    response($.map(results1, function(loc) {
                      return {
                        label  : loc.formatted_address,
                        value  : loc.formatted_address,
                        bounds   : loc.geometry.bounds
                      }
                    }));
                  }
                }
              });
            }
          });
        },
        select: function(event,ui){
          var pos = ui.item.position;
          var lct = ui.item.locType;
          var bounds = ui.item.bounds;

          if (bounds){
            map.fitBounds(bounds);
          }
        }
      });
    });

    
    $('input[type=text]').on('keyup', function(e) {
      if (e.which == 13) {
        e.preventDefault();
        searchPlace();
      }
    });

  });



  function searchPlace(){
    searchboxValue = $('#searchbox').val();
    $('#claim_place_address').val(searchboxValue);
    geocoder.geocode(
        {'address': searchboxValue},
        function(results, status) {
          if (status == google.maps.GeocoderStatus.OK) {
            var loc = results[0].geometry.location;
//            alert("lat=" + loc.lat());
//            alert("lng=" + loc.lng());

            mapOptions = {
              zoom: 18,
              center: new google.maps.LatLng(loc.lat(),loc.lng()),
              // disableDefaultUI: false,
              mapTypeId: google.maps.MapTypeId.ROADMAP,

              mapTypeControl: true,
              mapTypeControlOptions: {
                style: google.maps.MapTypeControlStyle.DROPDOWN_MENU
              },
              zoomControl: true,
              zoomControlOptions: {
                style: google.maps.ZoomControlStyle.SMALL
              },
              // disableDefaultUI: false,
              panControl: true,
              scaleControl: true,
              streetViewControl: true
            }

            var map = new google.maps.Map(document.getElementById("map-canvas"),mapOptions);
            claimPlaceLat = loc.lat();
            claimPlaceLng = loc.lng();

            new google.maps.Marker({
              position: new google.maps.LatLng(claimPlaceLat,claimPlaceLng ),
              map: map
            });

          }
          else {
            alert("Not found: " + status);
          }
        }
    );
  }

  function createPlace(){

    $('.createPlaceWraper').bPopup({
      zIndex:11,
      modalClose:true,
      onClose: function(){
        document.getElementsByClassName("createPlaceWraper").disabled = false;
        $('#createPlaceLat').val(0.0);
        $('#createPlaceLng').val(0.0);
        $('#createPlaceAddress').val(null);        
      }
    });
    $('#createPlaceAddress').append(searchboxValue);
    $('#createPlaceLat').val(claimPlaceLat);
    $('#createPlaceLng').val(claimPlaceLng);

    // alert("lat&lng="+ claimPlaceLat + "," + claimPlaceLng);
    // alert(searchboxValue);
  }

</script>

app/views/claim_places/show.html.erb
<div class="container shopContainer">
  <div class="storeName"> <%= @claimPlace.storeName %> </div>

  <address class="span12">
    <div class="claimPlace">
    <%= link_to("Edit Store", edit_claim_place_path(@claimPlace) ,
                :class => "btn btn-mini")%>

    <%= link_to("Post New Product", new_claim_place_product_path(@claimPlace) ,
                :class => "btn btn-mini btn-primary")%>
    </div>

    <a href="https://www.google.com.tw/maps/place/<%=@claimPlace.address%>/@<%= @claimPlace.latitude%>,<%= @claimPlace.longitude%>,20z" target="_blank">
      <img class="icon-location" src="/assets/icon-location.png">
      <strong><%= @claimPlace.address %></strong>
    </a>
    <br>

    <abbr title="Phone">Phone:</abbr> <%= @claimPlace.ownerPhone %><br>
    <a href="mailto:#"><%= @claimPlace.ownerEmail %></a>
  </address>

  <div class="storeDescription span12 ckeditor">
    <%= simple_format(@claimPlace.description) %>
  </div>

  <div class="productsLength" style="display: none"><%= @products.length %></div>

  <div class="productList">

    <% @products.each_with_index do |product,index| %>

      <div class="row-fluid product">
        <div class="span12 productName"><%= product.productName %></div>

        <div class="span6">
          <ol class="radarValue" style="display: none">
            <li><%= product.fragrance %></li>
            <li><%= product.flavor %></li>
            <li><%= product.aftertaste %></li>
            <li><%= product.acidity %></li>
            <li><%= product.body %></li>
            <li><%= product.balance %></li>
            <li><%= product.overall %></li>
          </ol>

          <table id="scaaItem" class=" table table-hover">
            <tr>
              <td>Fragrance</td>
              <td><%= product.fragrance %></td>
            </tr>
            <tr>
              <td>Flavor</td>
              <td><%= product.flavor %></td>
            </tr>
            <tr>
              <td>Aftertaste</td>
              <td><%= product.aftertaste %></td>
            </tr>
            <tr>
              <td>Acidity</td>
              <td><%= product.acidity %></td>
            </tr>
            <tr>
              <td>Body</td>
              <td><%= product.body %></td>
            </tr>
            <tr>
              <td>Uniformity</td>
              <td><%= product.uniformity %></td>
            </tr>
            <tr>
              <td>Balance</td>
              <td><%= product.balance %></td>
            </tr>
            <tr>
              <td>CleanCup</td>
              <td><%= product.cleanCup %></td>
            </tr>
            <tr>
              <td>Sweetness</td>
              <td><%= product.sweetness %></td>
            </tr>
            <tr>
              <td>Overall</td>
              <td><%= product.overall %></td>
            </tr>
            <tr>
              <td>Taint</td>
              <td><%= product.taint %></td>
            </tr>
            <tr>
              <td>Fault</td>
              <td><%= product.fault %></td>
            </tr>
            <tr class="success">
              <td>TotalScore</td>
              <td><%= product.totalScore %></td>
            </tr>
          </table>
        </div>

        <div class="span6">
          <div class="adminActions">
            <% if current_user != nil %>
              <% if product.user_id == current_user.id %>
                <%= link_to("Edit", edit_claim_place_product_path(product.claim_place_id, product), :class=>"btn btn-mini")%>
                <%= link_to("Delete", claim_place_product_path(product.claim_place_id, product), :class => "btn btn-mini",:method=>:delete,:confirm=>"Are you sure?")%>
              <% end %>
            <% end %>
          </div>

          <canvas id="coffeeRadarChart_<%= index %>" width="450px" height="380px"></canvas>

          <div class="description"> Description :
            <%= simple_format(product.description) %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

<style type="text/css">

</style>

<script type="text/javascript">

</script>